### ISSUE TITLE
Fragment Pattern 

### ISSUE THREAD

**Issue by ElhamFadel** [GSG-G11/tasty#18]
https://github.com/GSG-G11/tasty/blob/01548e4e85a1443f074fb37b2fc4728169452af5/src/components/Add.js#L9
Hi guys, I have a very small hint for you.
I noticed that you are using ```div``` tag as a Root for React component,
But that will be a consumer for memory,
So we don't need more to create an extra DOM node,
There's common component in React you can use it 
to return multiple elements (as a root)
called ***Fragment*** or you can use shortest from it using angle bracitce ***<> </>***
Best wishes,
Elham

**Comment by Fady-Alwazir** [comment]
Thank you

**Comment by farah2003** [comment]
thank you

**Comment by ElhamFadel** [comment]
> https://github.com/GSG-G11/tasty/blob/01548e4e85a1443f074fb37b2fc4728169452af5/src/components/Add.js#L9
> 
> 
> Hi guys, I have a very small hint for you.
> I noticed that you are using `div` tag as a Root for React component,
> But that will be a consumer for memory,
> So we don't need more to create an extra DOM node,
> There's common component in React you can use it
> to return multiple elements (as a root)
> called _**Fragment**_ or you can use shortest from it using angle bracitce _**<> </>**_
> Best wishes,
> Elham

[Also you can read thia](https://reactjs.org/docs/fragments.html) 

best
